### ISSUE TITLE
Replace PersistentDict with already existing lib

### ISSUE THREAD

**Issue by jpopelka** [user-cont/frambo#14]
Did I forget to use Google before implementing the [PersistentDict](https://github.com/user-cont/frambo/blob/master/frambo/dict_in_redis.py)?

- [persistent-dict](https://pypi.org/project/persistent-dict/), [repo](https://github.com/richardARPANET/persistent-dict)
- [Durabledict](https://pypi.org/project/durabledict/), [repo](https://github.com/disqus/durabledict/)

**Comment by TomasTomecek** [comment]
*replace 150 LoC with a library*:
* persistent-dict 0.1.1, Last released: Dec 23, 2017, https://github.com/richardasaurus/persistent-dict 404
* https://github.com/disqus/durabledict/, latest commit 4 years ago

I wish we had an AI platform which would tell me the above on its own.

**Comment by jpopelka** [comment]
> replace 150 LoC with a library:

frambo is not just 150LoC, it's also a library which
* requires (pulls in) A LOT of other libraries
* is not on PyPI (yes, that could be easily fixed)

>     * persistent-dict 0.1.1, Last released: Dec 23, 2017, https://github.com/richardasaurus/persistent-dict 404

correct github url is: https://github.com/richardARPANET/persistent-dict

Yes, they are old, but if they provide what we need ...

**Comment by jpopelka** [comment]
Whoops, I thought we're commenting https://github.com/packit-service/packit-service/issues/38
OK, you're right, the code can stay here, closing.

**Comment by jpopelka** [comment]
Or if we don't want to use any of the above existing libs (because they might be unmaintained), we can move our [PersistentDict](https://github.com/user-cont/frambo/blob/master/frambo/dict_in_redis.py) into a separate repo, so our other projects (https://github.com/packit-service/packit-service/issues/38) can use it without pulling in all the frambo dependencies.

EDIT: I'd be nice to keep git history while moving the file into a new repo, see for example: [1](https://gbayer.com/development/moving-files-from-one-git-repository-to-another-preserving-history/), [2](https://gist.github.com/whistler/de34b77aba2221ed8b2e), [3](https://stackoverflow.com/questions/40260649/move-file-to-another-git-repository-with-history), [4](https://stosb.com/blog/retaining-history-when-moving-files-across-repositories-in-git/)

**Comment by TomasTomecek** [comment]
or [5](https://blog.tomecek.net/post/git-magic-rewrite-history/) :P

**Comment by jpopelka** [comment]
* https://github.com/user-cont/persistentdict
* https://pypi.org/project/persistentdict

**Comment by jpopelka** [comment]
Removed in #15
